version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SlackApp-JiraHermes"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-peh5e6cowwxh"
s3_prefix = "SlackApp-JiraHermes"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
